### ISSUE TITLE
Изменение заметки

### ISSUE THREAD

**Issue by sereban-prog** [pi17zb-groupdynamics/svs_Calendar#20]
Добавить возможность редактировать данные уже существующей заметки, например при двойном клике на заметку в списке

**Comment by sereban-prog** [comment]
**Добавлено**
В текущей версии программы добавлена возможность редактирования заметок.
Для этого произведите двойной клик левой клавишей мыши (если вы не левша, иначе правой) на заметке которую хотите отредактировать.
**ПРОФИТ**

**Comment by VitaliyMitrofanov** [comment]
Спасибо, что уточнили! А амбидекстрам какую нажимать?
